### ISSUE TITLE
IndexError occurred when running SIMBA

### ISSUE THREAD

**Issue by hanfu-bios** [nerettilab/SIMBA3D#2] opened 2018-07-23 20:44 UTC
Hi,

I was trying to run SIMBA with my data, but I encountered an error which says 

  ```
File "/home/cai.507/anaconda2/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/cai.507/anaconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value

IndexError: index 3730545 is out of bounds for axis 0 with size 3730545
```

The data I used and .json file were attached in this post. Could somebody help me solve this problem?  

Thanks a lot!!

[simba_input.zip](https://github.com/nerettilab/SIMBA3D/files/2220959/simba_input.zip)

**Comment by michael-m-rosenthal** [comment] 2018-07-24 12:41
Hi,


It looks like an array is being iterated improperly. I will take a look.

Michael

On Jul 23, 2018 3:44 PM, "Han Fu" <notifications@github.com> wrote:

Hi,

I was trying to run SIMBA with my data, but I encountered an error which
says

File "/home/cai.507/anaconda2/lib/python2.7/multiprocessing/pool.py",
line 253, in map
  return self.map_async(func, iterable, chunksize).get()
File "/home/cai.507/anaconda2/lib/python2.7/multiprocessing/pool.py",
line 572, in get
  raise self._value

IndexError: index 3730545 is out of bounds for axis 0 with size 3730545

The data I used and .json file were attached in this post. Could somebody
help me solve this problem?

Thanks a lot!!

simba_input.zip
<https://github.com/nerettilab/SIMBA3D/files/2220959/simba_input.zip>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/2>, or mute the thread

**Comment by michael-m-rosenthal** [comment] 2018-07-24 13:41
When I run it with the command:

>simba3d -r taskBulkA.json

It starts running. I am running it now.

In the meantime, I have a few questions.
(1) how are you calling it?  (i.e. like above?)
(2) are you using python 2.7 ( I know it isn't supported anymore I just
hadn't ported yet)
(3) where is it crashing? Is it after running for a long time?
(4) this number 3730545, is that the size of the matrix? Or is that an
iteration it is breaking at?


On Jul 24, 2018 7:40 AM, "Michael Rosenthal" <michael.m.rosenthal@gmail.com>
wrote:

Hi,


It looks like an array is being iterated improperly. I will take a look.

Michael

On Jul 23, 2018 3:44 PM, "Han Fu" <notifications@github.com> wrote:

Hi,

I was trying to run SIMBA with my data, but I encountered an error which
says

File "/home/cai.507/anaconda2/lib/python2.7/multiprocessing/pool.py",
line 253, in map
  return self.map_async(func, iterable, chunksize).get()
File "/home/cai.507/anaconda2/lib/python2.7/multiprocessing/pool.py",
line 572, in get
  raise self._value

IndexError: index 3730545 is out of bounds for axis 0 with size 3730545

The data I used and .json file were attached in this post. Could somebody
help me solve this problem?

Thanks a lot!!

simba_input.zip
<https://github.com/nerettilab/SIMBA3D/files/2220959/simba_input.zip>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/2>, or mute the thread

**Comment by hanfu-bios** [comment] 2018-07-24 19:39
Hi Michael,

For your questions,

(1) I was calling it using `python ../SIMBA3D/SIMBA3D/run_simba3d.py -c 10 -r taskBulkA.json`.
(2) I am using Python 2.7.
(3) It crashed before the iterations, after it gave "number of points" and "curve dimension".
(4) The size of matrix is 2732. I have no clue what 3730545 represents.

Thanks very much for your assistance.

**Comment by michael-m-rosenthal** [comment] 2018-07-24 20:26
Unfortunately I was not able to reproduce the error. It runs for me.

I hadn't tried it with an anaconda install.

The multi processing module (a dependency) could have a problem in the
anaconda install or it might just be getting in the way of discovering the
problem.

Things to try
- updating the multiprocessing module.
- run without using the multiprocessing package

I will work on a script for running without using the multiprocessing.

In the meantime, please try to update your dependecy modules and see if
that helps.


Thank you,

Michael

On Jul 24, 2018 2:39 PM, "Han Fu" <notifications@github.com> wrote:

Hi Michael,

For your questions,

(1) I was calling it using python ../SIMBA3D/SIMBA3D/run_simba3d.py -c 10
-r taskBulkA.json.
(2) I am using Python 2.7.
(3) It crashed before the iterations, after it gave "number of points" and
"curve dimension".
(4) The size of matrix is 2732. I have no clue what 3730545 represents.

Thanks very much for your assistance.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/2#issuecomment-407527091>,
or mute
the thread

**Comment by michael-m-rosenthal** [comment] 2018-07-25 13:38
I made a solo version of the run script.
simba3d_taskrun_SOLO.py is a modified version of the run_simba3d.py script which avoids
creating multiprocessing pools altogether. It runs the same way only
without the cores.

The multiprocessing package can get in the way of debugging as it can block
error messages.

If you rerun your experiment with this I might get a more helpful error
message.

**Comment by michael-m-rosenthal** [comment] 2018-07-28 13:09
I am going to close this issue. If you rerun it with the script that doesn't call multiprocessing and get an error, please open another ticket and let me know. I hope it works for you and I am sorry I was not able to reproduce the error.

**Closed as completed by michael-m-rosenthal** 2018-07-28 13:09 UTC
